/**
 * Evidence generation helpers.
 * Extracted to allow clean mocking in tests.
 *
 * Requirements: 29.1, 29.2, 29.3, 29.4
 */

import { execSync } from "child_process";
import { readFileSync, existsSync, writeFileSync, mkdirSync } from "fs";
import path from "path";

// ---------------------------------------------------------------------------
// Stack Versions
// ---------------------------------------------------------------------------

export interface StackVersions {
  nextjs: string;
  react: string;
  typescript: string;
  python: string;
  polars: string;
}

export function getStackVersions(): StackVersions {
  const frontendPkgPath = path.resolve(process.cwd(), "package.json");
  let nextjs = "14.2.21";
  let react = "18.3.1";
  let typescript = "5.7.3";

  try {
    if (existsSync(frontendPkgPath)) {
      const pkg = JSON.parse(readFileSync(frontendPkgPath, "utf-8"));
      nextjs = pkg.dependencies?.next?.replace(/[\^~]/g, "") || nextjs;
      react = pkg.dependencies?.react?.replace(/[\^~]/g, "") || react;
      typescript = pkg.devDependencies?.typescript?.replace(/[\^~]/g, "") || typescript;
    }
  } catch {
    // Use defaults if parsing fails
  }

  // Python/Polars versions from known pyproject.toml
  const python = ">=3.11";
  const polars = "1.14.0";

  return { nextjs, react, typescript, python, polars };
}

// ---------------------------------------------------------------------------
// Commit Hash
// ---------------------------------------------------------------------------

export function getCommitHash(): string {
  // First check Vercel env vars (available in Vercel deployments)
  if (process.env.VERCEL_GIT_COMMIT_SHA) {
    return process.env.VERCEL_GIT_COMMIT_SHA;
  }

  // Fallback: try git command
  try {
    const hash = execSync("git rev-parse HEAD", { encoding: "utf-8" }).trim();
    return hash;
  } catch {
    return "unknown";
  }
}

// ---------------------------------------------------------------------------
// Test Results & Coverage
// ---------------------------------------------------------------------------

export interface TestResults {
  unit: { total: number; passed: number; failed: number; skipped: number };
  e2e: { total: number; passed: number; failed: number; skipped: number };
}

export interface CoverageMetrics {
  statements: number;
  branches: number;
  functions: number;
  lines: number;
}

export function getTestResults(): TestResults {
  const defaults: TestResults = {
    unit: { total: 0, passed: 0, failed: 0, skipped: 0 },
    e2e: { total: 0, passed: 0, failed: 0, skipped: 0 },
  };

  // Try to read vitest JSON results
  const vitestJsonPath = path.resolve(process.cwd(), "test-results", "results.json");
  if (existsSync(vitestJsonPath)) {
    try {
      const results = JSON.parse(readFileSync(vitestJsonPath, "utf-8"));
      defaults.unit = {
        total: results.numTotalTests || 0,
        passed: results.numPassedTests || 0,
        failed: results.numFailedTests || 0,
        skipped: results.numPendingTests || 0,
      };
    } catch {
      // Use defaults
    }
  }

  // Try to read Playwright JSON results
  const playwrightJsonPath = path.resolve(process.cwd(), "test-results", "playwright-results.json");
  if (existsSync(playwrightJsonPath)) {
    try {
      const results = JSON.parse(readFileSync(playwrightJsonPath, "utf-8"));
      defaults.e2e = {
        total: results.stats?.expected || 0,
        passed: results.stats?.expected || 0,
        failed: results.stats?.unexpected || 0,
        skipped: results.stats?.skipped || 0,
      };
    } catch {
      // Use defaults
    }
  }

  return defaults;
}

export function getCoverageMetrics(): CoverageMetrics {
  const defaults: CoverageMetrics = {
    statements: 0,
    branches: 0,
    functions: 0,
    lines: 0,
  };

  // Try to read coverage-summary.json (generated by vitest --coverage with v8)
  const coverageSummaryPath = path.resolve(process.cwd(), "coverage", "coverage-summary.json");
  if (existsSync(coverageSummaryPath)) {
    try {
      const summary = JSON.parse(readFileSync(coverageSummaryPath, "utf-8"));
      const total = summary.total;
      if (total) {
        defaults.statements = total.statements?.pct || 0;
        defaults.branches = total.branches?.pct || 0;
        defaults.functions = total.functions?.pct || 0;
        defaults.lines = total.lines?.pct || 0;
      }
    } catch {
      // Use defaults
    }
  }

  return defaults;
}

// ---------------------------------------------------------------------------
// Evidence Artifact Generation
// ---------------------------------------------------------------------------

export interface EvidencePayload {
  commitHash: string;
  buildDate: string;
  stack: StackVersions;
  tests: TestResults;
  coverage: CoverageMetrics;
  environment: string;
  dataProvenance: "REAL_DATA";
  generatedAt: string;
}

export function generateEvidenceArtifact(evidence: EvidencePayload): void {
  try {
    const now = new Date();
    const dateStr = now.toISOString().split("T")[0]; // YYYY-MM-DD
    const shortCommit = evidence.commitHash.substring(0, 7);

    const artifactsDir = path.resolve(
      process.cwd(),
      "artifacts",
      "evidence",
      `${dateStr}_${shortCommit}`
    );

    // Ensure directory exists
    mkdirSync(artifactsDir, { recursive: true });

    // Write evidence JSON
    const evidenceFilePath = path.join(artifactsDir, "evidence.json");
    writeFileSync(evidenceFilePath, JSON.stringify(evidence, null, 2), "utf-8");
  } catch {
    // Artifact generation is best-effort; don't fail the endpoint
  }
}
