#!/bin/bash
# =============================================================================
# generate-changelog.sh — Conventional Commits Changelog Generator
# =============================================================================
# Generates CHANGELOG.md from git history following Conventional Commits format.
# Links each entry to its associated ticket/requirement.
#
# Usage:
#   ./scripts/generate-changelog.sh [from_tag] [to_ref]
#
# Examples:
#   ./scripts/generate-changelog.sh              # All commits on current branch
#   ./scripts/generate-changelog.sh v0.1.0       # From v0.1.0 to HEAD
#   ./scripts/generate-changelog.sh v0.1.0 v0.2.0  # Between two tags
#
# REQ-27.3: Changelog vinculado a tickets con formato Conventional Commits
# =============================================================================

set -euo pipefail

FROM_REF="${1:-}"
TO_REF="${2:-HEAD}"
OUTPUT_FILE="CHANGELOG.md"

# Build git log range
if [ -n "$FROM_REF" ]; then
  RANGE="${FROM_REF}..${TO_REF}"
else
  RANGE="$TO_REF"
fi

echo "# Changelog — VantiOps 360" > "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "> Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$OUTPUT_FILE"
echo "> Range: ${RANGE}" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Function to extract and format commits by type
extract_type() {
  local type="$1"
  local header="$2"
  local commits

  commits=$(git log --oneline --format="%s|%h|%ai" "$RANGE" 2>/dev/null | grep -E "^${type}" || true)

  if [ -n "$commits" ]; then
    echo "### $header" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    while IFS='|' read -r subject hash date; do
      # Extract scope if present
      scope=$(echo "$subject" | grep -oP "(?<=\().*?(?=\))" || echo "")
      # Extract description (after ": ")
      desc=$(echo "$subject" | sed -E "s/^${type}(\([^)]*\))?!?:\s*//" || echo "$subject")
      # Extract ticket reference from commit body
      ticket=$(git log -1 --format="%b" "$hash" 2>/dev/null | grep -oP "(?<=Refs: )#[A-Z]+-[0-9]+" || echo "")
      req=$(git log -1 --format="%b" "$hash" 2>/dev/null | grep -oP "(?<=Requirement: )REQ-[0-9]+" || echo "")

      # Format entry
      entry="- "
      [ -n "$scope" ] && entry+="**${scope}:** "
      entry+="$desc (\`$hash\`)"
      [ -n "$ticket" ] && entry+=" $ticket"
      [ -n "$req" ] && entry+=" [$req]"

      echo "$entry" >> "$OUTPUT_FILE"
    done <<< "$commits"
    echo "" >> "$OUTPUT_FILE"
  fi
}

# Extract commits by type
extract_type "feat" "Features"
extract_type "fix" "Bug Fixes"
extract_type "perf" "Performance Improvements"
extract_type "refactor" "Refactoring"
extract_type "docs" "Documentation"
extract_type "test" "Tests"
extract_type "ci" "CI/CD"
extract_type "chore" "Maintenance"

# Check for breaking changes
breaking=$(git log --format="%s|%h" "$RANGE" 2>/dev/null | grep -E "!:" || true)
breaking_body=$(git log --format="%H" "$RANGE" 2>/dev/null | while read h; do
  body=$(git log -1 --format="%b" "$h" 2>/dev/null | grep "BREAKING CHANGE:" || true)
  [ -n "$body" ] && echo "$h|$body"
done || true)

if [ -n "$breaking" ] || [ -n "$breaking_body" ]; then
  echo "### ⚠️ Breaking Changes" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
  if [ -n "$breaking" ]; then
    while IFS='|' read -r subject hash; do
      desc=$(echo "$subject" | sed -E "s/^[a-z]+(\([^)]*\))?!:\s*//")
      echo "- $desc (\`$hash\`)" >> "$OUTPUT_FILE"
    done <<< "$breaking"
  fi
  echo "" >> "$OUTPUT_FILE"
fi

echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "*Generated by \`scripts/generate-changelog.sh\` using Conventional Commits standard.*" >> "$OUTPUT_FILE"

echo "✅ Changelog generated: $OUTPUT_FILE"
echo "   Commits analyzed from: $RANGE"
